version: 2

project_name: gradleconf

before:
  hooks:
    - go mod tidy

builds:
  - id: linmac
    env: [ CGO_ENABLED=0 ]
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
    dir: .
    main: ./cmd/gradleconf
    binary: gradleconf
  - id: windows
    env: [ CGO_ENABLED=0 ]
    targets:
      - windows_amd64
    dir: .
    main: ./cmd/gradleconf
    binary: gradleconf

checksum:
  name_template: 'checksums.txt'

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: jksolbakken
    name: gradleconf
  header: |
    ## gradleconf ({{ .Version }})

brews:
  - repository:
      owner: jksolbakken
      name: homebrew-tap
      token: "{{ .Env.BREW_PUSH_TOKEN }}"
    name: gradleconf
    homepage: "https://github.com/jksolbakken/gradleconf"
    description: "Opinionated tool for configuring single module Kotlin Gradle projects"
    directory: Formula
    install: |
      bin.install "gradleconf"
    test: |
      assert_match version, shell_output("#{bin}/gradleconf version")


