name: Publish release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-version:
    runs-on: ubuntu-latest
    name: set-version
    permissions:
      contents: read
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          persist-credentials: false
      - name: set version
        id: set-version
        run: |
          echo Faking a Semantic Version
          echo "version=1.$(date "+%Y%m%d%H%M%S")" >> ${GITHUB_OUTPUT}

  test:
    needs:
      - set-version
    runs-on: ubuntu-latest
    name: test
    permissions:
      contents: read
    steps:
      - name: Checkout latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          persist-credentials: false
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # ratchet:jdx/mise-action@v4
        with:
          cache: false
      - name: Run tests
        run: |
          mise i
          mise check
          mise test

  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write # for adding new releases
      id-token: write # for cosign
    name: release
    needs:
      - set-version
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cargowall
        uses: code-cargo/cargowall-action@fc9644606d84536b4e59a30ad2802904f7b4ff22 # ratchet:code-cargo/cargowall-action@v1
        mode: audit
        sudo-lockdown: true
        with:
          allowed-hosts: |
            *.github.com
      - name: Checkout latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # ratchet:jdx/mise-action@v4
        with:
          cache: false

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # ratchet:sigstore/cosign-installer@v4.0.0
        with:
          cosign-release: 'v3.0.6'

      - name: Create tag
        run: |
          git tag $VERSION
        env:
          VERSION: ${{ needs.set-version.outputs.version }}

      - name: build
        run: mise compile

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # ratchet:goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2.15.4
          args: release --config .goreleaser.yaml --clean --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BREW_PUSH_TOKEN: ${{ secrets.BREW_PUSH_TOKEN }}

